//Posición: En el indice
$(document).ready(function(){
	var frases = new Array();
	frases.push("<i>”espero q pasen una bonita velada con lighclaudio!”</i> - juaner");
	frases.push("<i>”Garcais”</i> - Wigazo");
	frases.push("<i>”Y espero que cuando vuelva, no cambien de color”</i> - Wigazo");
	frases.push("<i>”Wig, eso es idiota.”</i> - Elite");
	frases.push("<i>”Wigazo’s Bot Activated”</i> - Wigazo");
	frases.push("<i>”¿A dónde vas?”</i> - juaner");
	frases.push("<i>”James Bond will return...”</i> - Wigazo");
	frases.push("<i>”NYAN NYAN NYAN NYAN NYAN”</i> - Nyancated Forum");
	frases.push("<i>”ea ea ea”</i> - LightClaudio");
	frases.push("<i>”Siente el choke”</i> - LightClaudio");
	frases.push("<i>”...”</i> - Lirianer");
	frases.push("<i>”EXACTO”</i> - LightClaudio ");
	frases.push("<i>”O de la suerte”</i> - LightClaudio");
	frases.push("<i>”Chale”</i> - Introducida por Lirianer");
	frases.push("<i>”Cool”</i> - Introducida por Elite");
	frases.push("<i>”Jum...”</i> - Elite");
	frases.push("<i>”Odio a los n00bs.”</i> - TDD");
	frases.push("<i>”Odio a los negros”</i> - Risis ");
	frases.push("<i>”ESTAS REGLAS SON MUY INTERESANTES; ENHORABUENA EDUX 12!!”</i> - edux ");
	frases.push("<i>”NAVIDAD NAVIDAD SANTA ME FALLO”</i> - dekarserverbot");
	frases.push("<i>”SIIIIIIIIIIIIIYYYYYYYYY”</i> - dekarserverbot");
	frases.push("<i>”23!!!”</i> - Wigazo");
	frases.push("<i>”El 23 es nuestra luz, síguela y encontrarás la salvación.”</i> - Wigazo");
	frases.push("<i>” Hey! Wigazo! leave them 23 alone! All in all it's just another brick in the wall. All in all you're just another brick in the wall.”</i> - LightClaudio");
	frases.push("<i>”Reglas son reglas”</i> - juaner");
	frases.push("<i>”Tu Medidor de Infracciones Menores (MIM) sube un punto. Por favor lee las reglas.”</i> - Wigazo");
	frases.push("<i>”Me tratan de viejo gruñón.”</i> - Wigazo");
	frases.push("<i>”gente dejen de mencionar a avatar, me hacen sentir como un vampiro perdido en un foro de crepusculo”</i> - dekarserverbot");
	frases.push("<i>”MIS OJOS”</i> - dekarserverbot");
	frases.push("<i>”Nada nuevo o interesante”</i> - dekarserverbot");
	frases.push("<i>”Sos casi tan bueno como yo.”</i> - Vlady");
	frases.push("<i>”Leyendo archivos... “</i> - Wigazo");
	frases.push("<i>”Tiene lo suyo.”</i> - dekarserverbot");
	frases.push("<i>”@juaner has sido baneado por juaner”</i> - Chat’s information");
	frases.push("<i>”e_E”</i> - Elite");
	frases.push("<i>”D:”</i> - LightClaudio");
	frases.push("<i>”Esto no es un concurso de popularidad.”</i> - juaner");
	frases.push("<i>”Damian, me asustaste!”</i> - juaner");
	frases.push("<i>”Cambiemos de tema”</i> - juaner");
	frases.push("<i>”VENGA”</i> - KB");
	frases.push("<i>”wolaz 8)”</i> - KB");
	frases.push("<i>”Me gustan las tortugas”</i> - MXS");
	frases.push("<i>”Ponte el delantal y limpia las telarañas.”</i> - Elite ");
	frases.push("<i>”El delantal te queda mejor a vos.”</i> - Elite");
	frases.push("<i>”Si me necesitan, marquen 0800-2323-WIG”</i> - Wigazo");
	frases.push("<i>”No hay que arreglar lo que no está roto.”</i> - dekarserverbot");
	frases.push("<i>”Xhapsterion traductor Is back!”</i> - Xhaps");
	frases.push("<i>”¡Bienvenido al foro! ¿Te gusta crear himnos?”</i> - Mx3brainpower");
	frases.push("<i>”QUIERO JUGAR A UN JUEGO”</i> - Wigazo ");
	frases.push("<i>”EL DADO DECIDIRÁ TU DESTINO”</i> - Wigazo ");
	frases.push("<i>”No soy cool.”</i> - Elite");
	frases.push("<i>”Soy cool.”</i> - Elite");
	frases.push("<i>”Soy muy cool.”</i> - juaner");
	frases.push("<i>”Soy un tallarín que se mueve por aquí que se mueve por allá.”</i> - Elite");
	frases.push("<i>”Es Elite, Elite , Elite Elite Elite EEEEElite “</i> - Elite");
	frases.push("<i>”MXS Di algo!”</i> - Elite");
	frases.push("<i>”Juanes Danos el Foro”</i> - Darkesis");
	frases.push("<i>”LOOSERNENSE”</i> - Darkesis");
	frases.push("<i>”Nos han plagiado el foro”</i> - Staff");
	frases.push("<i>”CONTESTEME”</i> - grox2400 (Últimas palabras)");
	frases.push("<i>”TOMA”</i> - LightClaudio ");
	frases.push("<i>”Necesito más ibuprofeno.”</i> - Wigazo");
	frases.push("<i>”:roll:”</i> - Otro");
	frases.push("<i>”RWG, me das vergüenza.”</i> - Wigazo");
	frases.push("<i>”¡La piedra 23 será mía!”</i> - Wigazo ");
	frases.push("<i>”¿Algún juego para recomendarme?”</i> - juaner ");
	frases.push("<i>”Entro al chat cada tanto para sentirme como un Dios que vuelve de entre las sombras.”</i> - juaner");
	frases.push("<i>”LOL, Juanes.”</i> - Darkesis");
	frases.push("<i>”Rumba rumba rumba”</i> - MC_ZX y Dragon_Soul");
	frases.push("<i>”LOCA”</i> - Lirianer");
	frases.push("<i>”HAY UNA MUSICA RARA EN MI CASA”</i> - Samu");
	frases.push("<i>”No me hablen mal, yo soy un mensajero.”</i> - Kazini");
	frases.push("<i>”Todos fuimos o somos n00bs en algo.”</i> - Wigazo");
	frases.push("<i>”Exagerad@”</i> - juaner");
	frases.push("<i>”No me gusta que anden conspirando contra mí en su chat.”</i> - juaner (referencia a CG)");
	frases.push("<i>”Soy un cacahuete.“</i> - The_Peanut");
	frases.push("<i>”eco”</i> - The_Peanut");
	frases.push("<i>”Cafe cafe cafe cafe!!!”</i> - Elite");
	frases.push("<i>”Niños a los que les importa un pito la opinión de los demás, niños que nunca se han puesto a pensar seriamente sobre las cosas, niños, sólo niños...”</i> - Arwen");
	frases.push("<i>”Y hay algo mas que me inspira... BOYS DON'T CRY!!!”</i> - BETTER INJECTION");
	frases.push("<i>”Otra razón para odiarte.”</i> - Wigazo");
	frases.push("<i>”Dentro de unos años...”</i> - Lirianer");
	frases.push("<i>”Odio le estereotipo creador-creación”</i> - MXS");
	frases.push("<i>”No soy edux.”</i> - Edux");
	frases.push("<i>” Era mi primo/hermano/amigo/novio en la PC”</i> - Usuario con obvia doble cuenta");
	frases.push("<i>”JDF es el grupo VIRUS.”</i> - juaner");
	frases.push("<i>”¡Guerra de patadas!”</i> - Elite ");
	frases.push("<i>”No es flood, es funflood.”</i> - Elite");
	frases.push("<i>”No es Garra es Gaara.”</i> - Elite");
	frases.push("<i>”Cuéntame una historia.”</i> - Elite");
	frases.push("<i>”¿Qué hago?”</i> - Elite");
	frases.push("<i>”WIIIIIIIIII”</i> - Elite");
	frases.push("<i>”Dejen a mati en paz o los baneo.”</i> - Wigazo");
	frases.push("<i>”noc xq nunca netiedo lo q escribe keronaxd :S es como si fuera otro idioma... el caso.”</i> - juaner");
	frases.push("<i>”renucnio por que no se contar historias ni cantar :(”</i> - LightClaudio");
	frases.push("<i>”RENUNCIO”</i> - LightClaudio");
	frases.push("<i>”Chinga tu madre!”</i> - RWG");
	frases.push("<i>”Me joden los putacus, me jode el foro completo”</i> - Razor");
	frases.push("<i>”Niños, fuera de mi jardín.“</i> - Tío Augusto");
	frases.push("<i>”LUSA HIJO DE Censurado”</i> - Darkesis");
	frases.push("<i>”Santiago Huerta Hace Hoyos”</i> - MXS");
	frases.push("<i>”¡Me vengaré!”</i> - Talla");
	frases.push("<i>”como te vamos a odiar si solo te falta el altar”</i> - LightClaudio a Elite");
	frases.push("<i>”Oh canes del abismo, dibujen mi camino a seguir”</i> - Xhaps");
	frases.push("<i>”Sólo una cosa dekar... ¿Hay algo para ti que no sea arenoso, castroso, aburrido, amargado o llorón?”</i> - Arwen");
	frases.push("<i>”Adios ilusos”</i> - BETTER INJECTION");
	frases.push("<i>”how do i keep getting brought up here....?”</i> - Davo");
	frases.push("<i>”Traigo droga para los usuarios.”</i> - Kokodrilo");
	frases.push("<i>”Seguro es una doble cuenta... Pero, ¿de quién?”</i> - Wigazo");
	frases.push("<i>”Seguro tiene una doble cuenta... Pero, ¿cuál?”</i> - Wigazo");
	frases.push("<i>”Todos vuelven, todos vuelven.”</i> - Wigazo");
	frases.push("<i>”Sabía que volverías arrastrándote.”</i> - Wigazo");
	frases.push("<i>”I'M BACK IN BLACK”</i> - Dark Demon");
	frases.push("<i>”Edux, sé hombre y confiesa de una vez si no sos cobarde.”</i> - Wigazo");
	frases.push("<i>”Hey Ed! “</i> - Wigazo");
	frases.push("<i>”Otra misión JDF cumplida.”</i> - JDF");
	frases.push("<i>”¡Seré Capitán Alpha!”</i> - tomaslimer");
	frases.push("<i>”Wig, el administrador estrella!”</i> - tomaslimer");
	frases.push("<i>”Xido!”</i> - KB");
	frases.push("<i>”Otro premio regalado por totoi? Ya se esta convirtiendo en el Papa Noel del foro”</i> - GhOsT");
	frases.push("<i>”ES T-O-T-O-I”</i> - toitoi *Yao*");
	frases.push("<i>”Me da weba escribir”</i> - MC_ZX");
	frases.push("<i>”El MIM sube un punto. Cuidado, ya está en 5.”</i> - Wigazo");
	frases.push("<i>”¡Chauchas!”</i> - Lirianer");
	frases.push("<i>”¡Listones!”</i> - juaner");
	frases.push("<i>”mi renuncia es lo mejor para el foro”</i> - Lirianer ");
	frases.push("<i>”siento poner el foro en vaciones, pero wig me trata muy mal.”</i> - juaner");
	frases.push("<i>”siento q justos tengan q pagar por pecadores”</i> - juaner");
	frases.push("<i>”dile Wig Te Crees Mi Madre?Pues Toma Banneado xd”</i> - SSBBW");
	frases.push("<i>”si kieres decir algo mal de mi dilo”</i> - juaner (luego de castigar a Wigazo porque éste había dicho lo que pensaba de él)");
	frases.push("<i>”Te mandaré al espacio, Wheatley.”</i> - Wigazo");
	frases.push("<i>”¡Feliz día de la lechuga!”</i> - Wigazo");
	frases.push("<i>”¡Es la maldición del foro!”</i> - Wigazo");
	frases.push("<i>”¡Veo doble, 4 2d5s!”</i> - Wigazo");
	frases.push("<i>”No dudo en que sea tuyo,pero es mi deber como buen usuario asegurarme de que todos cumplen las reglas”</i> - Samu (en el concurso donde hizo trampa)");
	frases.push("<i>”Pasó un ángel.”</i> - sefirok");
	frases.push("<i>”USER WAS BANNED FOR THIS POST”</i> - dekarserverbot");
	frases.push("<i>”Mensos”</i> - dekarserverbot");
	frases.push("<i>”me banearon por una frase de CHESPIRITO”</i> - dekarserverbot");
	frases.push("<i>”Mi médico es el 23.”</i> - Wigazo");
	frases.push("<i>”Parece que se cayó del tercer piso y le afectó el golpe.”</i> - LightClaudio");
	frases.push("<i>”P*TOS JUEGOS”</i> - LightClaudio");
	frases.push("<i>”Error de tipeo.”</i> - sefirok");
	frases.push("<i>”Yello verde gente, ¿como estan por estos lares?”</i> - sefirok");
	frases.push("<i>”el foro se a degradado mucho”</i> - sefirok");
	frases.push("<i>”Qué feas caras, no me gustan.”</i> - sefirok");
	frases.push("<i>”Ya no hay tantos concursos, o template o actividades que insentiven a las personas a moverse en el foro”</i> - sefirok (en el momento más inoportuno)");
	frases.push("<i>”que hace alguien de 99 años jugando spore?”</i> - LightClaudio");
	frases.push("<i>”HOLA soy JUANERRRR no juanes”</i> - juaner");
	frases.push("<i>”WELCOME TO THE JUNGLE”</i> - TDD");
	frases.push("<i>”yo pienso q no es justo porque yo fui un colaborador hace tiempo y me gane el titulo de mod jr”</i> - 5m0okt ");
	frases.push("<i>”yo creo que seria bueno tener un moderador que mata negros xD”</i> - LightClaudio");
	frases.push("<i>”ELITE MOD = usara sus teclas especiales de BAN, CLEAR y KICK”</i> - Darkesis");
	frases.push("<i>”LCD is a registered mark from Darkesis Company Inc.”</i> - Darkesis");
	frases.push("<i>”EPIC MAGIC DANCE (y millones de girs bailando)”</i> - LeonTheLoller");
	frases.push("<i>”PAPELERA WOO HOO”</i> - dekarserverbot");
	frases.push("<i>”Así que no te vuelvas a meter con el foro. ¿Capiche?”</i> - JDF");
	frases.push("<i>”algum brasileiros?”</i> - Moe");
	frases.push("<i>”D'OH!”</i> - tomás kapo spore");
	frases.push("<i>”O Bob Patiño irá a su casa y se lo comerá.”</i> - Dark Grox");
	frases.push("<i>”BANÉENME SI QUIEREN”</i> - SporeOrigins");
	frases.push("<i>”Ahoi a todos!”</i> - CefaloSapiens");
	frases.push("<i>”Los pulpos dominarán al mundo.”</i> - CefaloSapiens");
	frases.push("<i>”Los archivos son evidencias.”</i> - Wigazo");
	frases.push("<i>”Menos mal que copio las convers.”</i> - Wigazo");
	frases.push("<i>”Elite lo ve todo E_E”</i> - Elite");
	frases.push("<i>”Wig me debes 1000&#36; acordate, algún día me vas a pagar.”</i> - Lirianer");
	frases.push("<i>”Voy a perder T_T”</i> - Elite");
	frases.push("<i>”Soy un relleno”</i> - MXS");
	frases.push("<i>”MXS está en estado EMO.”</i> - MXS");
	frases.push("<i>”Nadie quiere a Elite.”</i> - Elite");
	frases.push("<i>”Siempre que llego están discutiendo.”</i> - MXS al resto de JDF");
	frases.push("<i>”Bebito llorón.”</i> - Dekarserverbot a sefirok");
	frases.push("<i>”JDF - M: RM (Misión: Robot Malvado)”</i> - JDF (Primera misión)");
	frases.push("<i>”¡Hereje!”</i> - Wigazo a Elite");
	frases.push("<i>”Pinches ateos pendejos.”</i> - Dekarserverbot");
	frases.push("<i>”Chupamedias, chupamedias everywhere.”</i> - Wigazo");
	frases.push("<i>”Detesto que hablen de mí, a mis espaldas.”</i> - Elite");
	frases.push("<i>”No te doy otra nomás porque...”</i> - Dekarserverbot");
	frases.push("<i>”Wigazo [JDF] Wigazo [JDF] Wigazo [JDF] Wigazo [JDF] Wigazo [JDF] Wigazo [JDF]...”</i> - Elite");
	frases.push("<i>”Dejen de hablar de Chuck o los baneo.”</i> - sefirok");
	frases.push("<i>”Soy la profeta del coolsismo.”</i> - Elite");
	frases.push("<i>”¡Soy el profeta del 23!”</i> - Wigazo");
	frases.push("<i>”Me caí del piso 23 y me rompí 23 huesos. Si me caía del 22, no sobrevivía.”</i> - Wigazo");
	frases.push("<i>”Elite, eres muy obvia.”</i> - MXS");
	frases.push("<i>”¡No soy Wigzago o Wizago, soy Wigazo!”</i> - Wigazo a juaner");
	frases.push("<i>”¿Por qué no hablan de mí? :(”</i> - juaner");
	frases.push("<i>”¡ODIO EL ROSA!”</i> - Elite");
	frases.push("<i>”¡AMO EL ROSA!”</i> - LolipopElite");
	frases.push("<i>”(CyG) Wigazo [JDF] tienes algun problema con migo que cada vez que hablo me haces la contra como si me tuvieras rencor”</i> - 5m0okt ");
	frases.push("<i>”Amenazaste con hakear el foro. ¿Disculpa? ¿Cómo lo harás? ¿Con raymans?”</i> - Elite");
	frases.push("<i>”No me importa lo del foro, nadie aquí es tan estúpido como para creerlo, bueno, nadie salvo Plaxaris92 ”</i> - Errónea predicción de 3lite (En presencia de Plaxaris92)");
	frases.push("<i>”no te juntes con esa chusma”</i> - dekarserverbot");
	frases.push("<i>”mala cosa mala cosa”</i> - juaner");
	frases.push("<i>”y conoci al presidente de los estados unidos OTRA VEZ”</i> - dekarserverbot");
	frases.push("<i>”a todos os gusta demasiado el sexo y creo que la unica que lo ha orivadi es arwen”</i> - Kokodrilo");
	frases.push("<i>”¿Qué hay si Dumdon quiere ser chico? ¡Yo te protegeré pequeño Dumdon!”</i> - Razor, cuando 3lite le cambió el género a Dumdon ");
	frases.push("<i>”¡No quiero estar ausente!”</i> - Andalaosa");
	frases.push("<i>”¡¿Dónde está Xhaps?! ¡Debo decirle que será padre!—¿Dónde está mi esposa muerta? ¡Quiero decirle que quiero que sea madre!” </i> - 3lite y Razor hablando de la novela");
	frases.push("<i>”Carajo!”</i> - Ghost");
	frases.push("<i>”Elite jamás me cambiaría el género a mi”</i> - Errónea predicción de Dumdon");
	frases.push("<i>”Fantasmita sexy~”</i> - 3lite cuando cambia el género de Ghost");
	frases.push("<i>”¡No me interrumpas, estoy hablando con mi esposa muerta! *Mirada*”</i> - Razor en la novela ");
	frases.push("<i>”hay yo hoy vi unas botas en oferta, divinas! Pero mi novio Rozart no me las quiso comprar, asi que termine con el”</i> - Razor en la noche de locas");
	frases.push("<i>”SPAAAAAACE!!!!!”</i> - Razor");
	frases.push("<i>”Estúpido y sensual {USERNAME}”</i> - Razor");
	frases.push("<i>”Deseo una patata. :odioso:”</i> - Patata Fan Club");
	frases.push("<i>”PROTESTO”</i> - dekarserverbot");
	frases.push("<i>”TENGO DERECHO A DESCREER Y A EXPRESARLO, ESO NO ES INSULTAR”</i> - JoseGarcia");
	frases.push("<i>”Y si no, HAY TORRETA!”</i> - Tomas Kapo Spore 2011");
	frases.push("<i>”ROLEA TU FUKING IMPERIO”</i> - Vinnie Sift");
	frases.push("<i>”mmm”</i> - Kokodrilo");
	frases.push("<i>”Yo quiero mi penechorizo *mentira*”</i> - DigiDSoul");
	frases.push("<i>”Cosas japonesas... *infinito*”</i> - Mx3brainpower");
	frases.push("<i>”Hola baldosa caminante!”</i> - Vinnie a Andalosa");
	frases.push("<i>”Dumdom, tu no puedes ni armar dos frases en japonés...”</i> - Xhaps");
	frases.push("<i>”Qué tal?”</i> - Mx3brainpower");
	frases.push("<i>”Tanto hablar de comida mi dio hambre y me fui a preparar el sesayuno.”</i> - Mx3brainpower");
	frases.push("<i>”como dice nuestro nada poderoso amigo esto es spam puro”</i> - dekarserverbot ");
	frases.push("<i>”Pesadilla Fuera”</i> - pesadilla");
	frases.push("<i>”Rammu {USERNAME}”</i> - Alegorn");
	frases.push("<i>”Me voy a comer :/ PERO NO PALOMAS ¬¬”</i> - Razor");
	frases.push("<i>”Sólo una cosa dekar... ¿Hay algo para ti que no sea arenoso,  castroso, aburrido, amargado o llorón?”</i> - Arwen");
	frases.push("<i>”¿Dónde está ese perro con mi café?”</i> - Imperatrum DG");
	frases.push("<i>”¿Con ”tú” te referías a mí?”</i> - DigiDSoul");
	frases.push("<i>”está de spora madre”</i> - Josgrox");
	frases.push("<i>”Si no era por un meteoro, ahora seguiríamos usando computadoras, pero nuestras madres no nos mentirían cundo dicen que salimos de un huevo.  *yao*”</i> - Vinnie Sift");
	frases.push("<i>”Arwen ,se tu nombre y apellidos ,te llamas MARÍA DOMÍNGUEZ”</i> - Lechuza");
	frases.push("<i>”Odio esto esto es solo Basura!! Aquí solo hay BASURA”</i> - DigiDSoul");
	frases.push("<i>”Los moderadores son tontos estúpidos e imbeciles, hay un tal otro que es un orto y un fantasma gordo de mierd*”</i> - DigiDSoul");
	frases.push("<i>”Elite es una tonta come café de mierd* y MXS una tortuga retrasada”</i> - DigiDSoul");
	frases.push("<i>”KB es una gorda que no cabe en mi armario y TKS es un pene”</i> - DigiDSoul");
	frases.push("<i>”Totoi es un cabrón y me chupa la almeja además todo esto es mied* pura mierd*a sois caca”</i> - DigiDSoul");
	frases.push("<i>”Dark es un put* Bob de mierd*, jony es una mierd* de mierd* de dinosaurio”</i> - DigiDSoul");
	frases.push("<i>”Wig es un cabrón de mierd* que me obliga a comer cucarachas”</i> - DigiDSoul");
	frases.push("<i>”Razor es un put* espacial de mierd*”</i> - DigiDSoul");
	frases.push("<i>”Xhaps se pasa el dia comiendo vacas de mierd*”</i> - DigiDSoul");
	frases.push("<i>”SO ES UN SOSO”</i> - DigiDSoul");
	frases.push("<i>”Juaner una put* zorra!!!!!”</i> - DigiDSoul");
	frases.push("<i>”Me encanto! *5puntos*”</i> - Costi");
	frases.push("<i>”El freedom no quita imaginación, sino que te quita los límites de la imaginación.”</i> - Wigazo");
	frases.push("<i>”Dark Injection *infinito*”</i> - Medio foro");
	frases.push("<i>”Apoyo enérgicamente esta propuesta.”</i> - Imperatrum DG");
	frases.push("<i>”ARGUEN Y DARKARSERVERBOT NO ESTAN DISCUTIENDO EN EL CHAT. ES... MI REGALO DE CUMPLEAÑOS?”</i> - Razor");
	frases.push("<i>”No puedo hablar sin faltas *challenge denied*” - ”lla ce me bolo la cabetha *odioso*”</i> - Mx3");
	frases.push("<i>”adios dessgradecifos incredulos” - ”lo siento me equibocado estoy con el movil”</i> - julia911");
	frases.push("<i>”bueno,es solo un juego,no todos piensan igual que tu”</i> -  Errónea negación de Rhine");
	frases.push("<i>”*Lanza una pezuña a Cora*”</i> - Wigazo");
	frases.push("<i>”Si no mejoras tu ortografía, mi ojos lloraran letras”</i> - Lechuza");
	frases.push("<i>”qe tiene de malo hablar cn faltas de ortografia? ustedes sn muy viejos, actualizence a la era moderna chotos”</i> - Hell Goblin");
	frases.push("<i>”[Soy feo, pero soy muy suave. Mp3] *chino*”</i> - Espía chino");
	frases.push("<i>”Lechuza,yo se lo vi a mi perro,no tengo dinero para comprarle un calzonsillo”</i> - Hell Goblin");
	frases.push("<i>”Se remueve la censura a pedido de los usuarios mal hablantes”</i> - Mx3");
	frases.push("<i>”No se juzga a un foro por su DG. *TrueStory*”</i> - Wigazo");
	frases.push("<i>”DEFINITIVAMENTE,puedo declararte como el usuario que capta menos sarcasmo que un sofa”</i> - Rhine");
	frases.push("<i>”PITUFOS MALNACIDOS”</i> - Totoi");
	frases.push("<i>”Como te hago un hijo?”</i> - Bato");
	frases.push("<i>”pork me nombras a mi?”</i> - N00b víctima del USERNAME");
	frases.push("<i>”me han dicho escroto de cabra... me voy del foro para siempre, antes esto era un refugio para mi, pero ahora todo se trata de escrotos. Dejare el foro por que se esta pudriendo por esto...”</i> - dekar");
	frases.push("<i>”Cambiemos de Conservación”</i> - Lechuza");
	frases.push("<i>”Me gusta el helado”</i> - Dumdon");
	frases.push("<i>”SIGUE MEJORANDO”</i> - Eduardochifull");
	frases.push("<i>”El miembro '{USERNAME}' ha efectuado la acción siguiente: Lanzar Dados”</i> - El Señor de los Dadillos");
	frases.push("<i>”EPILEPSIAAAA SENSUAL”</i> - Lechuza");
	frases.push("<i>”Sol puedo decir”</i> - julia911");
	frases.push("<i>”Más que ofendido deberías sentirte glorificado por tu anomalía cerebral”</i> - Xhaps");
	frases.push("<i>”HEY BATO, PORQUE NO TE CREAS UN CEREBRO EN POWERPOINT? A VER SI LO LOGRAS!!”</i> - Ajo");
	frases.push("<i>”Todos pueden encontrar amistades en la S2 ;) , hasta Bato *truestory*”</i> - Mx3");
	frases.push("<i>”Se que te desconectaras”</i> - Rhine");
	frases.push("<i>”no, no me desconectará”</i> - La Máscara");
	frases.push("<i>””POR LA LIBERACION DE MAURI” (?”</i> - Wigazo");
	frases.push("<i>”mira el lado bueno, podrás regodearte de que has sido baneado del foro más cool de toda la web”</i> - Razor");
	frases.push("<i>”Todos los artistas odian sus creaciones... Por que, por mas que la gente diga que esta bueno, en el fondo de su corazon, el artista sabe la verdad... Que es una reverenda cagada....”</i> - Vinnie");
	frases.push("<i>”Spore Sam es sexy como el culo de MasterJ”</i> - Lechuza");
	frases.push("<i>”felicidades, PERO VALE... Y ESTE SEÑOR QUIEN ES!?!?!?!?!?!?!?”</i> - Dekar");
	frases.push("<i>”@ : v”</i> - Fantasma de TKS");
	frases.push("<i>”Ven que se parece al RTI?”</i> - Mur-mai-der");
	frases.push("<i>”Solo una parida D=”</i> - Rhinestone");
	frases.push("<i>”PUMBA INFRACCIÓN EN TODA LA BOCA!”</i> - Blood");
	frases.push("<i>”Eso es todo camaradas. *camarada*”</i> - Glumyglu");
	frases.push("<i>”¡Por la Revolución del Quijote! *camarada*”</i> - Los camaradas haciendo la revolución en FDF");
	frases.push("<i>”Ban Ban Ban!”</i> - Staff");

	$("#frase-celebre").html(frases[Math.floor(Math.random()*frases.length)]);
});